"""Emit a compose overlay that differs from the shipped config by exactly the flags you name.

    python bench/arm_compose.py --out /tmp/arm.yaml --quantization=vtl_fp8
    python bench/arm_compose.py --out /tmp/arm.yaml --max-num-scheduled-tokens=1024
    python bench/arm_compose.py --out /tmp/arm.yaml '~--max-num-scheduled-tokens'   # drop it

WHY THIS EXISTS. Two reasons, and the second is the important one.

1. ``VTL_QUANT=vtl_fp8`` is named as *the* W4A8-vs-FP8 A/B mechanism in two places
   (``vtl/patches/quant_w4a8.py`` and the ``make verify`` output) and **has never existed** --
   nothing reads that variable. Quantization is a ``--quantization`` CLI flag, and every other
   interesting knob (``--max-num-scheduled-tokens``, ``--max-num-seqs``, ``--compilation-config``)
   is a CLI flag too. Only ``VTL_W4A8_SCHEDULE`` is env-driven, which is why ``sweep-schedule``
   could be written as a plain env loop and nothing else can.

2. Without this, sweeping a flag means hand-editing ``docker-compose.yaml`` per arm -- and that
   file is the SUBMISSION ARTIFACT. Forgetting to revert one literal after a sweep ships a
   config nobody chose. This never writes to it: it reads the fully-resolved config out of
   ``docker compose config`` and emits a throwaway overlay.

WHY THE WHOLE COMMAND LIST IS COPIED. A compose overlay's ``command:`` REPLACES the base list
rather than merging into it, so an overlay carrying one flag would drop the other eighteen and
boot a server with no ``--model``. Copying the resolved list is what makes an arm differ by
exactly one thing -- which is also the property ``bench/compare.py`` assumes when it ranks arms.

The base is read through ``docker compose config``, so this stays correct if the overlay chain
changes; there is no second YAML parser here to drift from the real one.
"""

import argparse
import json
import subprocess
import sys


def flag_name(entry):
    """The comparable name of a command entry: ``--foo=bar`` and ``--foo`` both -> ``--foo``.

    Positional/non-flag entries (``-O3``) return themselves, so they are only ever replaced by
    an identical string and never accidentally matched by a ``--`` override.
    """
    return entry.split("=", 1)[0] if entry.startswith("--") else entry


def apply_overrides(command, overrides):
    """Return a new command list with ``overrides`` applied. Pure; see _selfcheck.

    Each override is either ``--flag=value`` / ``--flag`` (replace in place if the flag is
    already present, else append) or ``~--flag`` (remove it). Replacing IN PLACE rather than
    append-and-let-argparse-win keeps the emitted list readable and means a duplicate flag can
    never appear -- vLLM's argparse would silently take the last one, which is exactly the kind
    of thing that makes an arm quietly not be the arm you think it is.
    """
    out = list(command)
    for ov in overrides:
        if ov.startswith("~"):
            target = flag_name(ov[1:])
            out = [e for e in out if flag_name(e) != target]
            continue
        target = flag_name(ov)
        for i, entry in enumerate(out):
            if flag_name(entry) == target:
                out[i] = ov
                break
        else:
            out.append(ov)
    return out


def resolve_command(compose_files):
    """The shipped command list, as docker itself resolves it across the overlay chain."""
    argv = ["docker", "compose"]
    for f in compose_files:
        argv += ["-f", f]
    argv += ["config", "--format", "json"]
    proc = subprocess.run(argv, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit(f"docker compose config failed:\n{proc.stderr.strip()}")
    return json.loads(proc.stdout)["services"]["model"]["command"]


def render(command, note):
    # json.dumps output is valid YAML (YAML 1.2 is a JSON superset), which sidesteps quoting the
    # --compilation-config entry -- it contains braces, quotes and spaces, and hand-rolled YAML
    # quoting of it is a boot failure waiting to happen.
    return (
        "# GENERATED by bench/arm_compose.py -- do not edit, do not commit.\n"
        f"# {note}\n"
        "# Overrides the base command list wholesale (compose replaces, never merges).\n"
        "services:\n"
        "  model:\n"
        f"    command: {json.dumps(command)}\n"
    )


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--out", required=True, help="overlay path to write")
    p.add_argument(
        "--compose-file", action="append", default=None,
        help="repeatable; defaults to the docker-compose.yaml in cwd",
    )
    p.add_argument(
        "overrides", nargs="*",
        help="--flag=value / --flag to set, ~--flag to remove",
    )
    # The no-op guard below is a typo catcher, and it is exactly wrong for `make ab`: the
    # CONTROL arm of an A/B restates the value the shipped config already has, so it changes
    # nothing BY CONSTRUCTION. Without this the control can never be booted through the same
    # overlay path as the treatment -- and booting them differently is how you measure the
    # overlay instead of the flag.
    p.add_argument(
        "--allow-unchanged", action="store_true",
        help="do not fail when the overrides are a no-op (A/B control arm)",
    )
    args, unknown = p.parse_known_args()
    # argparse swallows anything starting with '-' as an option, so the flags we are asked to
    # SET land in `unknown`. Both buckets are overrides; order between them is preserved well
    # enough because a flag can only be named once in a sane invocation.
    overrides = list(args.overrides) + list(unknown)
    if not overrides:
        sys.exit("no overrides given -- an arm identical to the base is not an arm")

    files = args.compose_file or ["docker-compose.yaml"]
    base = resolve_command(files)
    command = apply_overrides(base, overrides)
    if command == base and not args.allow_unchanged:
        sys.exit(f"overrides {overrides} changed nothing -- check the flag spelling")

    note = "arm = shipped config + " + " ".join(overrides)
    with open(args.out, "w") as f:
        f.write(render(command, note))
    print(f"{args.out}: {note}")
    for ov in overrides:
        print(f"  {ov}")


def _selfcheck():
    base = ["-O3", "--model=/model", "--quantization=vtl_w4a8", "--max-num-seqs=70"]

    # replace in place, not append -- position is preserved and no duplicate appears
    got = apply_overrides(base, ["--quantization=vtl_fp8"])
    assert got == ["-O3", "--model=/model", "--quantization=vtl_fp8", "--max-num-seqs=70"], got
    assert base[2] == "--quantization=vtl_w4a8", "must not mutate the caller's list"

    # a flag absent from the base is appended
    got = apply_overrides(base, ["--max-num-scheduled-tokens=1024"])
    assert got[-1] == "--max-num-scheduled-tokens=1024" and len(got) == 5, got

    # removal, for the "prove the flag itself is neutral" arm
    assert apply_overrides(base, ["~--max-num-seqs"]) == base[:3]
    assert apply_overrides(base, ["~--not-there"]) == base  # removing an absent flag is a no-op

    # several at once, and a valueless flag
    got = apply_overrides(base, ["--quantization=vtl_fp8", "--enforce-eager", "~--model"])
    assert got == ["-O3", "--quantization=vtl_fp8", "--max-num-seqs=70", "--enforce-eager"], got

    # a bare positional like -O3 is never matched by a --flag override
    assert apply_overrides(["-O3"], ["--O3=x"]) == ["-O3", "--O3=x"]

    # flag_name normalises both spellings to the same key
    assert flag_name("--foo=bar") == flag_name("--foo") == "--foo"
    assert flag_name("-O3") == "-O3"

    # the rendered overlay must round-trip as YAML *and* preserve the awkward entry verbatim
    hard = '--compilation-config={"pass_config": {"fuse_norm_quant": true}}'
    text = render(apply_overrides(base + [hard], ["--quantization=vtl_fp8"]), "t")
    body = text.split("command: ", 1)[1]
    assert json.loads(body)[-1] == hard, body
    print("arm_compose self-check ok")


if __name__ == "__main__":
    if "--self-check" in sys.argv:
        _selfcheck()
    else:
        main()
