services:
  vllm:
    image: vllm/vllm-openai:v0.25.0

    network_mode: host

    volumes:
      - /home/team17/Qwen3.5-122B-A10B-FP8:/model:ro

    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"

    command:
      - --model
      - /model
      - --host
      - 0.0.0.0
      - --port
      - "9005"

      - --max-model-len
      - "204800"

      - --max-num-seqs
      - "5"

      - --kv-cache-dtype
      - "fp8"

      - --kv-offloading-size
      - "64"

      - --kv-offloading-backend
      - "native"

      - --enable-prefix-caching
      - --served-model-name
      - Qwen3.5-122B-A10B-FP8

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]